# Generated by Django 5.1.7 on 2025-04-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_userprofile_profile_picture"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
