# Generated by Django 5.1.7 on 2025-04-20 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_delete_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("district", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "farmer_type",
                    models.CharField(
                        choices=[
                            ("crop", "Crop Farmer"),
                            ("livestock", "Livestock Farmer"),
                            ("mixed", "Mixed"),
                            ("organic", "Organic / Sustainable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("farm_size", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "soil_type",
                    models.CharField(
                        choices=[
                            ("clay", "Clay"),
                            ("loamy", "Loamy"),
                            ("sandy", "Sandy"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "irrigation_method",
                    models.CharField(
                        choices=[
                            ("drip", "Drip"),
                            ("rainfed", "Rain-fed"),
                            ("sprinkler", "Sprinkler"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("experience", models.CharField(max_length=50)),
                ("preferred_crops", models.TextField()),
                ("seasonal_crops", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
