# Generated by Django 5.1.7 on 2025-04-20 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="seasonal_crops",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="seasonal_details",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="experience",
            field=models.PositiveIntegerField(help_text="Years of experience"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="farm_size",
            field=models.DecimalField(
                decimal_places=2, help_text="In acres", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="farmer_type",
            field=models.CharField(
                choices=[
                    ("crop", "Crop Farmer"),
                    ("livestock", "Livestock Farmer"),
                    ("mixed", "Mixed Farming"),
                    ("organic", "Organic/Sustainable"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="irrigation_method",
            field=models.CharField(
                choices=[
                    ("drip", "Drip"),
                    ("sprinkler", "Sprinkler"),
                    ("surface", "Surface"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="preferred_crops",
            field=models.CharField(help_text="Comma-separated list", max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="soil_type",
            field=models.CharField(
                choices=[
                    ("sandy", "Sandy"),
                    ("clay", "Clay"),
                    ("silt", "Silt"),
                    ("peat", "Peat"),
                    ("chalk", "Chalk"),
                    ("loam", "Loam"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
